name: weather_app
description: "Weather app"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.5
  go_router: ^14.1.3
  shared_preferences: ^2.2.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_screenutil: ^5.9.1
  jwt_decoder: ^2.0.1
  logger: ^2.3.0
  get_it: ^7.7.0
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  build_runner: ^2.4.10
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  image: assets/icons/app_icon.png
  color: "#000000"
  android_12:
    color: "#000000"
    image: assets/icons/app_icon.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
